# Generated by Django 4.2.13 on 2026-06-15 06:37

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('rc_photo', models.ImageField(upload_to=core.models.bike_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), core.models.validate_image_size])),
                ('insurance_photo', models.ImageField(upload_to=core.models.bike_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), core.models.validate_image_size])),
                ('pollution_photo', models.ImageField(upload_to=core.models.bike_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), core.models.validate_image_size])),
                ('buyer_name', models.CharField(max_length=160)),
                ('buyer_phone', models.CharField(blank=True, max_length=20)),
                ('buyer_address', models.TextField(blank=True)),
                ('buyer_photo', models.ImageField(upload_to=core.models.bike_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), core.models.validate_image_size])),
                ('seller_name', models.CharField(max_length=160)),
                ('seller_phone', models.CharField(blank=True, max_length=20)),
                ('seller_address', models.TextField(blank=True)),
                ('seller_photo', models.ImageField(upload_to=core.models.bike_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), core.models.validate_image_size])),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
