# Generated by Django 4.2.13 on 2026-06-17 13:27

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bikerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikerecord',
            name='buyer_identity_photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bike_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), core.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='bikerecord',
            name='noc_photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bike_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), core.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='bikerecord',
            name='seller_identity_photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bike_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), core.models.validate_image_size]),
        ),
    ]
