# Generated by Django 4.2.13 on 2026-06-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bikerecord_buyer_identity_photo_bikerecord_noc_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikerecord',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='bikerecord',
            name='seller_name',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
