# Generated by Django 4.2.13 on 2026-06-17 16:28

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_bikerecord_insurance_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikerecord',
            name='buyer_photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bike_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), core.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='bikerecord',
            name='seller_photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bike_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), core.models.validate_image_size]),
        ),
    ]
