# Generated by Django 4.2.13 on 2026-06-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_bikerecord_buyer_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikerecord',
            name='buyer_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
