# Generated by Django 4.2.13 on 2026-06-18 06:31

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_bikerecord_buyer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeDocumentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('rc', 'RC'), ('insurance', 'Insurance'), ('pollution', 'Pollution'), ('noc', 'NOC'), ('buyer_identity', 'Buyer Identity'), ('seller_identity', 'Seller Identity')], max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=core.models.bike_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_photos', to='core.bikerecord')),
            ],
        ),
    ]
