# Generated by Django 4.2.13 on 2026-06-20 12:48

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_bikerecord_buyer_identity_photo_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikerecord',
            name='buyer_photo',
        ),
        migrations.RemoveField(
            model_name='bikerecord',
            name='seller_photo',
        ),
        migrations.AddField(
            model_name='bikerecord',
            name='buyer_identity_photo_1',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bike_upload_path),
        ),
        migrations.AddField(
            model_name='bikerecord',
            name='buyer_identity_photo_2',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bike_upload_path),
        ),
        migrations.AddField(
            model_name='bikerecord',
            name='buyer_identity_photo_3',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bike_upload_path),
        ),
        migrations.AddField(
            model_name='bikerecord',
            name='buyer_identity_photo_4',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bike_upload_path),
        ),
        migrations.AddField(
            model_name='bikerecord',
            name='buyer_identity_photo_5',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bike_upload_path),
        ),
        migrations.AddField(
            model_name='bikerecord',
            name='insurance_photo_1',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bike_upload_path),
        ),
        migrations.AddField(
            model_name='bikerecord',
            name='insurance_photo_2',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bike_upload_path),
        ),
        migrations.AddField(
            model_name='bikerecord',
            name='insurance_photo_3',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bike_upload_path),
        ),
        migrations.AddField(
            model_name='bikerecord',
            name='insurance_photo_4',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bike_upload_path),
        ),
        migrations.AddField(
            model_name='bikerecord',
            name='insurance_photo_5',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bike_upload_path),
        ),
        migrations.AddField(
            model_name='bikerecord',
            name='noc_photo_1',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bike_upload_path),
        ),
        migrations.AddField(
            model_name='bikerecord',
            name='noc_photo_2',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bike_upload_path),
        ),
        migrations.AddField(
            model_name='bikerecord',
            name='noc_photo_3',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bike_upload_path),
        ),
        migrations.AddField(
            model_name='bikerecord',
            name='noc_photo_4',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bike_upload_path),
        ),
        migrations.AddField(
            model_name='bikerecord',
            name='noc_photo_5',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bike_upload_path),
        ),
        migrations.AddField(
            model_name='bikerecord',
            name='pollution_photo_1',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bike_upload_path),
        ),
        migrations.AddField(
            model_name='bikerecord',
            name='pollution_photo_2',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bike_upload_path),
        ),
        migrations.AddField(
            model_name='bikerecord',
            name='pollution_photo_3',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bike_upload_path),
        ),
        migrations.AddField(
            model_name='bikerecord',
            name='pollution_photo_4',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bike_upload_path),
        ),
        migrations.AddField(
            model_name='bikerecord',
            name='pollution_photo_5',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bike_upload_path),
        ),
        migrations.AddField(
            model_name='bikerecord',
            name='rc_photo_1',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bike_upload_path),
        ),
        migrations.AddField(
            model_name='bikerecord',
            name='rc_photo_2',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bike_upload_path),
        ),
        migrations.AddField(
            model_name='bikerecord',
            name='rc_photo_3',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bike_upload_path),
        ),
        migrations.AddField(
            model_name='bikerecord',
            name='rc_photo_4',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bike_upload_path),
        ),
        migrations.AddField(
            model_name='bikerecord',
            name='rc_photo_5',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bike_upload_path),
        ),
        migrations.AddField(
            model_name='bikerecord',
            name='seller_identity_photo_1',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bike_upload_path),
        ),
        migrations.AddField(
            model_name='bikerecord',
            name='seller_identity_photo_2',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bike_upload_path),
        ),
        migrations.AddField(
            model_name='bikerecord',
            name='seller_identity_photo_3',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bike_upload_path),
        ),
        migrations.AddField(
            model_name='bikerecord',
            name='seller_identity_photo_4',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bike_upload_path),
        ),
        migrations.AddField(
            model_name='bikerecord',
            name='seller_identity_photo_5',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bike_upload_path),
        ),
    ]
